
work_dir: ./work_dir/ntu/xsub/trial1

# feeder
debug: False

stream: SKEL

feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /home/uniwa/students3/students/22905553/linux/phd_codes/Olympics/Data/Olympic_Openpose/Female_train_joint_v3.npy
  label_path: /home/uniwa/students3/students/22905553/linux/phd_codes/Olympics/Data/Olympic_Openpose/Female_train_label_v3.pkl
  video_path: None #/media/22905553/F020DDF820DDC5AE/Olympic_v1/video_frames/
  seq_len: -1
  video_feature: False
  video_only: False
  label_smooth: True
  normalization: True
  debug: False


class_loss: False
pretrain: False

num_worker: 16

test_feeder_args:
  data_path: /home/uniwa/students3/students/22905553/linux/phd_codes/Olympics/Data/Olympic_Openpose/Female_test_joint_v3.npy
  label_path: /home/uniwa/students3/students/22905553/linux/phd_codes/Olympics/Data/Olympic_Openpose/Female_test_label_v3.pkl
  video_path: None #/media/22905553/F020DDF820DDC5AE/Olympic_v1/video_frames/
  seq_len: -1
  video_feature: False
  video_only: False
  label_smooth: True
  normalization: True
  debug: False
  
pretrain_JFE: True

# model
model1: model_msg3d.msg3d.Model
model_args:
  num_class: 1
  num_point: 25
  num_person: 1
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.msg3d_olympic.AdjMatrixGraph
#  drop_out: 0.2

model2: model.seq_model.MLP
seq_model_args:
  input_size: 875
  inchannel: 192
  NL_mode: embedded #concatenate
  NL_dimention: 1
  channel_kernel: 16
  seq_kernel: 59
  drop_out: 0.2
  hidden1: 192
  hidden2: 96
  stream: 1s

# optim
optimizer: Adam  #SGD
weight_decay: 0.0001
base_lr: 0.01
step: [10,20,30, 40]
step_size: 20
#warmup_epoch: 5
cosine_schedule: False

# training
#alpha: 0.9
#temperature: 10
num_epoch: 50
#temp: 0.07
device: [0]
batch_size: 4
forward_batch_size: 2
test_batch_size: 4
nesterov: True
save_score: True

#teacher_weights: /home/uniwa/students3/students/22905553/linux/phd_codes/action_recognition/pretrianed_model/msg3d/ntu60-xsub-joint-paper.pt
#weights1: /home/uniwa/students3/students/22905553/linux/phd_codes/Olympics/Olympic_code/trial30/weights/weights-35-1540.pt
#weights2: /home/uniwa/students3/students/22905553/linux/phd_codes/Olympics/Olympic_code/trial30/weights/seq-weights-35-1540.pt

#checkpoint: /home/uniwa/students3/students/22905553/linux/phd_codes/Action_recognition/Trial35/checkpoints/checkpoint-35-fwbz32-21525.pt


